# Generated by Django 3.0.2 on 2020-01-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeattendance',
            old_name='emp_id',
            new_name='emp',
        ),
    ]
